---
- name: Install docker-ce and docker-compose
  apt:
    update_cache: yes
    name:
      - docker-compose

- name: Create docker cert directory
  file:
    path: "/etc/docker/certs.d/{{ HARBOR_FQDN }}"
    state: directory
    mode: 0644

- name: Copy ca certificate
  copy:
    src: ./roles/vault/config/files/ca.crt
    dest: "/etc/docker/certs.d/{{ HARBOR_FQDN }}/ca.crt"
    mode: 0644
  notify: Restart docker service

- name: Copy certificate and private key
  copy:
    src: "./roles/harbor/prepare/files/{{ item.src }}"
    dest: "/etc/docker/certs.d/{{ HARBOR_FQDN }}/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: "{{ HARBOR_FQDN }}.crt" , dest: "{{ HARBOR_FQDN }}.crt" }
    - { src: "{{ HARBOR_FQDN }}.key" , dest: "{{ HARBOR_FQDN }}.key" }
  notify: Restart docker service

- name: Copy daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: Restart docker service

- name: Add vagrant user to docker group
  user:
    name: vagrant
    group: docker
