---
- name: Add apt signing key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add hashicorp repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com buster main
    state: present

- name: Install Vault
  apt:
    name:
      - vault
